name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-26 12 *'

  workflow_dispatch:                             # allow to manually start the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1621696
          leaderboard: "https://adventofcode.com/2021/leaderboard/private/view/1591922.json"
          session: ${{ secrets.AOC_SESSION }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
